language: python
python:
  - "3.7"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - sudo apt-get install -y libudev-dev
install:
  - pip3 install homeassistant
  - pip3 install websocket
  - pip3 install bs4
script:
  - touch fullchain.pem
  - touch privkey.pem
  - hass -c . --script check_config
