- id: '1582890671844'
  alias: 'Notify: Update Available'
  description: Sends a telegram message when an update is available
  trigger:
  - entity_id: sensor.update_available
    from: 'false'
    platform: state
    to: 'true'
  action:
  - data:
      message: Meister, die Home Assistant version *{{ states("sensor.last_ha_version")}}* ist verfügbar. Derzeit läuft die Version {{ states("sensor.current_ha_version")}}.
    service: notify.telegram
  - service: input_text.set_value
    data_template:
      entity_id: input_text.last_known_version_update
      value: '{{ states(''sensor.last_ha_version'') }}'
- id: '1584961424173'
  alias: 'Service: make full backup'
  description: Erstellt jeden Sonntag ein volles Backup
  trigger:
  - at: 03:00:00
    platform: time
  condition:
  - condition: time
    weekday:
    - sun
  action:
  - data_template:
      name: Backup {{ now().strftime('%Y-%m-%d') }}
    service: hassio.snapshot_full
