
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# SSL Access
http:
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: True
  login_attempts_threshold: 2

# Text to speech
tts:
  - platform: google_translate

media_player:
  - platform: enigma2
    host: 10.0.0.104
    mac_address: !secret vuplus_mac
    password: !secret vusolo4k_password
    name: "Vu+ Solo4K"
  - platform: samsungtv_custom
    host: 10.0.0.103
    mac: !secret sasmsung_mac
    port: 8002
    timeout: 30
    protocol: ws
    sourcelist: '{"AV-Receiver": "KEY_HDMI1", "Receiver": "KEY_HDMI2", "Switch": "KEY_HDMI3", "Mac": "KEY_HDMI4"}'

switch:
  - platform: wake_on_lan
    host: 10.0.0.102
    mac: !secret arbeitszimmer_mac
    name: "Arbeitszimmer"
  - platform: wake_on_lan
    host: 10.0.0.101
    mac: !secret diskstation_mac
    name: "Diskstation"

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_token
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id

automower:
  username: !secret husqvarna_username
  password: !secret husqvarna_password

camera:
  name: Miki
  platform: generic
  still_image_url: !secret husqvarna_maps_url
  limit_refetch_to_url_change: true

sensor:
  - platform: waste_at_bmv
    ort: !secret bmv_ort
    strasse: !secret bmv_strasse
    hausnummer: !secret bmv_hausnummer
  - platform: template
    sensors:
      gelbersack_text:
        value_template: "{{states.sensor.waste_gelber_sack.attributes.display_text_long}}"
        friendly_name: 'Gelber Sack'
        icon_template: mdi:sack
      papiertonne_text:
        value_template: "{{states.sensor.waste_papier.attributes.display_text_long}}"
        friendly_name: 'Papier'
        icon_template: mdi:delete-empty
      restmuell_text:
        value_template: "{{states.sensor.waste_restmull.attributes.display_text_long}}"
        friendly_name: 'Restmüll'
        icon_template: mdi:trash-can-outline

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml
  
logger:
  default: info
  logs:
    custom_components.waste_at_bmv: debug

logbook:
  exclude:
    entities:
#      - automation.*
      - device_tracker.automower_h_170805572_164914249
      - device_tracker.christian_iphone
      - sensor.christian_activity
      - sensor.christian_average_active_pace
      - sensor.christian_battery_level
      - sensor.christian_battery_state
      - sensor.christian_bssid
      - sensor.christian_connection_type
      - sensor.christian_distance
      - sensor.christian_floors_ascended
      - sensor.christian_floors_descended
      - sensor.christian_last_update_trigger
      - sensor.christian_sim_1
      - sensor.christian_ssid
      - sensor.christian_steps

history:
  exclude:
    entities:
#      - automation.*
      - binary_sensor.updater
      - device_tracker.automower_h_170805572_164914249
      - sensor.christian_average_active_pace
      - sensor.christian_battery_level
      - sensor.christian_battery_state
      - sensor.christian_bssid
      - sensor.christian_connection_type
      - sensor.christian_distance
      - sensor.christian_floors_ascended
      - sensor.christian_floors_descended
      - sensor.christian_last_update_trigger
      - sensor.christian_sim_1
      - sensor.christian_ssid
      - sensor.christian_steps
      - sensor.gelbersack_text
      - sensor.papiertonne_text
      - sensor.restmuell_text

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
