background: var(--background-image)
custom_header:
  compact_mode: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)
  header_text: Zuhause
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'
title: Home
views:
  - badges:
      - entity: person.christian
      - entity: person.elias
      - entity: person.anna_mavie
    cards:
      - entity: weather.home
        type: weather-forecast
      - type: entities
        title: Abfalltermine
        show_header_toggle: false
        entities:
        - entity: sensor.gelbersack_text
        - entity: sensor.papiertonne_text
        - entity: sensor.restmuell_text
      - cards:
          - entity: light.blumenlampe
            hold_action:
              action: more-info
            name: Blumenlampe
            show_icon: true
            show_name: true
            state_color: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: light.elias_light
            hold_action:
              action: more-info
            name: Elias Zimmer
            show_icon: true
            show_name: true
            state_color: true
            tap_action:
              action: toggle
            type: entity-button
        title: Licht
        type: horizontal-stack
      - cards:
          - entity: switch.arbeitszimmer
            icon: 'mdi:desktop-mac'
            type: entity-button
            state_color: true
          - entity: switch.diskstation
            icon: 'mdi:nas'
            type: entity-button
            state_color: true
        title: Computer
        type: horizontal-stack
      - cards:
        - type: picture-entity
          entity: camera.miki
        - type: entities
          entities:
            - vacuum.miki
        type: vertical-stack
      - entity: media_player.samsung_tv_remote
        type: media-control
        name: Samsung TV
      - entity: media_player.vu_solo4k
        type: media-control
      - entity: media_player.onkyo
        type: media-control
        name: Onkyo
    icon: 'mdi:home'
    panel: false
    path: default_view
    title: Überblick
