# Name: LoraTap RR400W Tuya Smart Life Wifi Relay Receiver
# Link to device: https://de.aliexpress.com/item/33005382815.html
# The device only switches L+N to the output pins. You cannot control the input for the relay.
#
# My working template
# 12    out   x    Relay
# 13    in    -    Pairing button, used as a switch on the relay


substitutions:
  device_name: switch_wlan_fence_gate
  device_description: Schalter Tor Zaun
  friendly_name: Switch fence gate
  short_name: Fence Gate

esphome:
  name: ${device_name}
  comment: ${device_description}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wlan_ssid
  password: !secret wlan_password
  manual_ip:
    static_ip: 10.0.0.204
    gateway: 10.0.0.138
    subnet: 255.255.255.0
    dns1: 10.0.0.134
    dns2: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${short_name} AP"
    password: !secret captive_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable Over The Air update (OTA)
ota:

# Enable web server
web_server:
  port: 80

sensor:
# report WLAN strength
  - platform: wifi_signal
    name: ${friendly_name} Signal
    update_interval: 60s
# Reports how long the device has been powered (in minutes)
  - platform: uptime
    name: ${friendly_name} Uptime
    filters:
      - lambda: return x / 60.0;
    unit_of_measurement: minutes

switch:
# provide a reboot
- platform: restart
  name: "${friendly_name} REBOOT"
# Relay action
- platform: gpio
  name: ${friendly_name}
  pin: GPIO12
  id: relay1
  restore_mode: ALWAYS_OFF

binary_sensor:
# Reports when the button is pressed
- platform: gpio
  device_class: power
  pin:
    number: GPIO13
    inverted: True
  name: "Switch ${short_name}"
  id: switch1
  on_press:
    then:
      - switch.toggle: relay1
  internal: true

text_sensor:
# Reports the ESPHome Version with compile date
  - platform: version
    name: ${friendly_name} ESPHome Version
