automation:
- id: '1606158583703'
  alias: Blinds down on sundown
  description: 'Fährt die Rollos am Abend runter'
  trigger:
    - platform: sun
      event: sunset
      offset: "+00:45:00"
  action:
    - service: switch.turn_on
      entity_id: switch.blind_kitchen_left_down
    - service: switch.turn_on
      entity_id: switch.blind_kitchen_right_down
    - service: switch.turn_on
      entity_id: switch.blind_livingroom_door_down
  mode: single

history:
  exclude:
    entities:
      - automation.blinds_down_on_sundown
